language: ruby
notifications:
  email: false
rvm:
  - 2.5.5
script: bundle exec rake ci

env:
  global:
    - CC_TEST_REPORTER_ID=778807d5fff912e1ee31e2c0d92968fd1e46fb2a93049cacba0a9cdd260eea19

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
