development:
  url: https://stacks.stanford.edu/image/iiif
test:
  url: https://stacks-test.stanford.edu/image/iiif
staging:
  url: https://stacks.stanford.edu/image/iiif
production:
  url: https://stacks.stanford.edu/image/iiif
